### PR TITLE
fix: introduce safeNamehash

### LINKED ISSUE #2876: Crash report: `Error: STRINGPREP_CONTAINS_UNASSIGNED`
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: STRINGPREP_CONTAINS_UNASSIGNED
```

## Stacktrace

```
Error: STRINGPREP_CONTAINS_UNASSIGNED
    at https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1137959
    at Array.forEach (<anonymous>)
    at y (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1137922)
    at k (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1138563)
    at https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:377646
    at Sn (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:377871)
    at ua (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1249509)
    at Ha (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1259076)
    at $u (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1302800)
    at Ps (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1289050)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

### PR DESCRIPTION
**Pull request by NoahZinsmeister**
closes #2876 

seems like there's probably some deeper unicode issue going on here, but this at least fixes the immediate problem for those with emojis in their ENS names

### CODE REVIEW

File: src/utils/safeNamehash.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import { namehash } from '@ethersproject/hash'
+
+export function safeNamehash(name?: string): string | undefined {
+  if (typeof name === 'undefined') return undefined
```
Comment (zzmp) [inline src/utils/safeNamehash.ts:4]: prefer `if (name === undefined)`

File: src/utils/safeNamehash.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+  try {
+    return namehash(name)
```
Comment (zzmp) [inline src/utils/safeNamehash.ts:7]: Did you open an issue with @ethersproject? We should be linking a relevant issue here as a comment, so it can be cleaned up later if/when they resolve it.

**Review by zzmp — CHANGES_REQUESTED** [review]

**Comment by NoahZinsmeister** [comment]
tracking in ethers: https://github.com/ethers-io/ethers.js/issues/2376
